### ISSUE TITLE
HA 2022.7.0b0: Platform unifiprotect does not generate unique IDs.

### ISSUE THREAD

**Issue by Bascht74** [briis/pyunifiprotect#207]
Hi, 

I get the following error with the new HA Beta: 
I don't think I got this error before...

```
Logger: homeassistant.components.binary_sensor
Source: helpers/entity_platform.py:620
Integration: Binärsensor ([documentation](https://rc.home-assistant.io/integrations/binary_sensor), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+binary_sensor%22))
First occurred: 22:51:19 (1 occurrences)
Last logged: 22:51:19

Platform unifiprotect does not generate unique IDs. ID 74ACB9005A9A_motion already exists - ignoring binary_sensor.carport_motion
```

**Comment by Bascht74** [comment]
I cannot delete that entity...

diagnose information:
[config_entry-unifiprotect-0781e33dd77712af25f8e996fa10a80e.json.txt](https://github.com/briis/pyunifiprotect/files/9014686/config_entry-unifiprotect-0781e33dd77712af25f8e996fa10a80e.json.txt)

**Comment by AngellusMortis** [comment]
Please provide [debug log](https://rc.home-assistant.io/integrations/unifiprotect#enabling-debug-logging) of HA during setup.

**Comment by AngellusMortis** [comment]
Nevermind, report to HA core.

**Comment by Bascht74** [comment]
@AngellusMortis OK, it said: 
You are running version 2.1.1-beta.5 of UniFi Protect, which is an Early Access version. Early Access versions of UniFi Protect are not supported for Home Asssitant. If have an error, please report errors to https://github.com/briis/pyunifiprotect first. DO NOT REPORT EA ISSUES TO HOME ASSISTANT CORE. It is recommended you downgrade to a stable version. https://www.home-assistant.io/integrations/unifiprotect#downgrading-unifi-protect.

btw: There is some sensitive information in the diagnose information, like my position: 

```
      "locationSettings": {
        "isAway": true,
        "latitude": 5X.320048629170714,
        "longitude": 9.XX9854523803605,
        "isGeofencingEnabled": true,
```
IDs:
```
      "hardwareId": "493b6xxx-d3d8-4cd5-9b95-ccaxxx47e372",
      "anonymousDeviceId": "f4bxxxac-94cc-47f4-aff9-61dxxxa48e",
      "id": "9a0a7cexxxx6e25eaaf678",
```

and access information: 
```
    "authUserId": "a89e83c91xxxxxxxxxx342744",
    "accessKey": "0781442567968:c38caeeb368xxxxxxxxxx....xxxxxxxxx832cca72af",
```

(put some "x" in those).
Are those lines information that need to be in the diag file that you share e.g. via github?
If not, should I open another issue at core or is this something that needs to be done here?

Sebastian

**Comment by AngellusMortis** [comment]
Yeah, that message is mostly get issues from new Protect versions. This is actually not from a new Protect version, but a new HA version. So, it is a HA issue. Sorry for the confusion. 

Please make a separate issue (in this repo) for the `locationSettings` settings. That is something I do not have enabled on my console and missed it. I apologize for it. All of the other "ids", I assure you are not real. They have all be randomized so they do not match the real values. You can the URL `/proxy/protect/api/bootstrap` on your console to see the real values.
