### ISSUE TITLE
Uncontrolled Resource Consumption in pillow

### ISSUE THREAD

**Issue by briis** [briis/pyunifiprotect#44]
I got a security alert from *dependabot* highlightning that `pillow` should be upgraded to minimum version 8.3.2. I can see that the two files `requirements_all.txt` and `requirements_test.txt` are autogenerated, so I am not exactly sure how to correct that. They both contain version 8.3.1 of `pillow`

@bdraco: Can you tell me how to fix this, or fix it?

**Comment by bdraco** [comment]
Looks like dependabot auto generated a PR to fix it. I merged it: https://github.com/briis/pyunifiprotect/pull/43

Should be all good now.  It only affected the CI&tests and not production code so probably nothing to worry about.

**Comment by briis** [comment]
Thanks. Good to know.
