### ISSUE TITLE
Error when running unifi-protect sensor

### ISSUE THREAD

**Issue by briis** [briis/pyunifiprotect#77]
After the latest updates to the module, I get the below error when issuing the command `unifi-protect sensor`. It does display the data first, but then it closes up with this error.

```log
Task exception was never retrieved
future: <Task finished name='Task-5' coro=<BaseApiClient._setup_websocket() done, defined at /workspaces/pyunifiprotect/pyunifiprotect/unifi_protect_server.py:335> exception=RuntimeError('Session is closed')>
Traceback (most recent call last):
  File "/workspaces/pyunifiprotect/pyunifiprotect/unifi_protect_server.py", line 336, in _setup_websocket
    await self.ensure_authenticated()
  File "/workspaces/pyunifiprotect/pyunifiprotect/unifi_protect_server.py", line 258, in ensure_authenticated
    await self.authenticate()
  File "/workspaces/pyunifiprotect/pyunifiprotect/unifi_protect_server.py", line 272, in authenticate
    response = await self.request("post", url=url, json=auth)
  File "/workspaces/pyunifiprotect/pyunifiprotect/unifi_protect_server.py", line 143, in request
    response = await req_context.__aenter__()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1117, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 381, in _request
    raise RuntimeError("Session is closed")
RuntimeError: Session is closed
````

**Comment by briis** [comment]
Just asked the guy with the UFP Sense device to give me some new event data. And he got this error when trying to run the `unifi-protect generate-sample-data` as you instructed him
<img width="626" alt="140040307-d832f9d3-5048-4b5a-b4fc-d682c9c7042b" src="https://user-images.githubusercontent.com/24776272/140041029-e7281bcb-00e7-4ddd-a15d-0dc2e79be710.png">
.

**Comment by AngellusMortis** [comment]
The first one looks like an odd race condition with the async call stack that you can ignore. I can probably add more code to make sure it does not happen, but you still got what you wanted from it.

Basically:

1. Login into UFP
2. Dump data from update
3. close ascync io session
4. Wait for "all tasks to complete"
5. `_setup_websocket` is finally call _after_ you are trying to exit and the session is already closed...

The second one looks like a network/configuration error. Did he mistype the IP for his UFP instance? It is getting a 404 on `/api/auth/login`, which is definitely the correct URL.

**Comment by AngellusMortis** [comment]
An open/close _should_ look like this (WS message, no event):

```json
"action": {
    "action": "update",
    "newUpdateId": "c132efe5-3f47-4a8c-b1f7-33b19ea05572",
    "modelKey": "sensor",
    "id": "6096619d02c50a03e7000788"
},
"data": {
    "isOpened": false,
    "openStatusChangedAt": 1635654008703
}
```

I think I mentioned it before, but the WS events are just overlaid directly onto the bootstrap object for the device. So if the device closes, the `isOpened` would change to `false` and the `openStatusChangedAt` would be the new timestamp.

**Comment by briis** [comment]
Closing. We have discussed this in the DM.
